import type { Choices, ResolvedChoices, Step, StepId } from "./types";

export const STEPS: readonly Step[] = [
  {
    id: "reference",
    branch: "base",
    gallery: "app",
    question: "Which product is the reference?",
    why: "Every later step defaults to what this product does. You confirm or deviate.",
    options: [
      { id: "linear", label: "Linear", note: "Dense, 13px chrome, cool gray, indigo, sidebar, hairlines." },
      { id: "vercel", label: "Vercel", note: "14px, pure neutral, black accent, top nav, soft shadows." },
      { id: "stripe", label: "Stripe", note: "14px, cool neutral, violet, sidebar, shadows, editorial landing." },
      { id: "notion", label: "Notion", note: "15px, warm neutral, black accent, borderless tables, generous." },
      { id: "raycast", label: "Raycast", note: "13px, dark-first, red accent, rounded, dark showcase landing." },
      { id: "ramp", label: "Ramp", note: "Exacting finance UI, acid green, compact density, operational proof." },
      { id: "apple", label: "Apple", note: "Giant centered type, product-led media, full-bleed chapters." },
      { id: "raindrop", label: "Raindrop", note: "Dark agent tooling, green signal, product trace, sticky storytelling." },
      { id: "mercury", label: "Mercury", note: "Warm editorial fintech, generous space, composed product imagery." },
      { id: "cashapp", label: "Cash App", note: "Black and bright green, giant type, rounded mobile-first play." },
      { id: "airbnb", label: "Airbnb", note: "Warm marketplace, photographic cards, soft depth, comfortable density." },
      { id: "figma", label: "Figma", note: "Creative canvas, art-led color, interactive product demonstrations." },
      { id: "cursor", label: "Cursor", note: "Warm dark developer tool, restrained chrome, code-forward product proof." },
      { id: "supabase", label: "Supabase", note: "Dark developer platform, green accent, grid structure, dashboard proof." },
      { id: "posthog", label: "PostHog", note: "Playful developer suite, warm canvas, orange signal, dense product cards." },
      { id: "attio", label: "Attio", note: "Editorial precision, monochrome CRM, compact data surfaces." },
      { id: "resend", label: "Resend", note: "Monochrome developer infrastructure, dark canvas, code and email proof." },
    ],
  },
  {
    id: "typeface",
    branch: "base",
    gallery: "app",
    question: "Which typeface?",
    why: "Carries 70–95% of rendered characters. Everything else is tuned to it.",
    options: [
      { id: "inter", label: "Inter", note: "The default of the field. Neutral, huge x-height, great at 13px." },
      { id: "geist", label: "Geist", note: "Vercel's. Slightly narrower and warmer than Inter." },
      { id: "plex", label: "IBM Plex Sans", note: "More character, wider. Reads editorial." },
      { id: "instrument", label: "Instrument Sans", note: "Geometric, friendly. Consumer feel." },
      { id: "system", label: "System", note: "SF on Mac, Segoe on Windows. Zero bytes, native feel." },
    ],
  },
  {
    id: "mono",
    branch: "base",
    gallery: "app",
    question: "Which mono, for identifiers and code?",
    why: "Appears in paths, ids, timestamps, code blocks. Must pair with the sans.",
    options: [
      { id: "geist-mono", label: "Geist Mono", note: "Pairs with Inter and Geist." },
      { id: "jetbrains", label: "JetBrains Mono", note: "Taller, more distinct glyphs. Reads as code." },
      { id: "plex-mono", label: "IBM Plex Mono", note: "Pairs with Plex Sans; slab-ish." },
      { id: "system-mono", label: "System mono", note: "SF Mono / Consolas. Zero bytes." },
    ],
  },
  {
    id: "neutral",
    branch: "base",
    gallery: "app",
    question: "Neutral temperature?",
    why: "The gray scale is 90% of every screen. Temperature sets the whole mood.",
    options: [
      { id: "cool", label: "Cool", note: "Blue-tinted gray. Linear, Stripe. Reads technical." },
      { id: "neutral", label: "Neutral", note: "True gray. Vercel. Reads exact." },
      { id: "warm", label: "Warm", note: "Sand/stone. Notion. Reads calm, paper-like." },
      { id: "tinted", label: "Tinted", note: "Mauve, carries a hint of the accent. Reads designed." },
    ],
  },
  {
    id: "contrast",
    branch: "base",
    gallery: "app",
    question: "Contrast level?",
    why: "Linear generates its theme from base, accent and contrast. This is the third knob.",
    options: [
      { id: "soft", label: "Soft", note: "Tinted canvas, faint borders. Quieter, lower AA margin." },
      { id: "standard", label: "Standard", note: "White canvas, step-6 borders. The field default." },
      { id: "high", label: "High", note: "Pure white/black, strong borders. Accessibility variant." },
    ],
  },
  {
    id: "accent",
    branch: "base",
    gallery: "app",
    question: "One accent?",
    why: "Buttons, links, focus, selection. One hue; status colors are separate.",
    options: [
      { id: "indigo", label: "Indigo", note: "Linear." },
      { id: "blue", label: "Blue", note: "Safe, expected." },
      { id: "violet", label: "Violet", note: "Stripe." },
      { id: "teal", label: "Teal", note: "Distinct from status green." },
      { id: "green", label: "Green", note: "Reads 'go'; collides with success." },
      { id: "orange", label: "Orange", note: "Warm, energetic." },
      { id: "crimson", label: "Crimson", note: "Raycast." },
      { id: "neutral", label: "Neutral", note: "Black/white primary. Vercel, Notion." },
    ],
  },
  {
    id: "radius",
    branch: "base",
    gallery: "app",
    question: "Corner radius?",
    why: "One value drives controls, cards and menus. Sets tone more than hue does.",
    options: [
      { id: "sharp", label: "4px", note: "Crisp, tool-like." },
      { id: "medium", label: "6px", note: "Linear, Vercel." },
      { id: "round", label: "8px", note: "Stripe, Raycast." },
      { id: "soft", label: "10px", note: "Consumer, friendly." },
      { id: "pill", label: "16px", note: "Consumer and mobile surfaces with visibly rounded controls." },
    ],
  },
  {
    id: "depth",
    branch: "base",
    gallery: "app",
    question: "Depth by border or shadow?",
    why: "Decides how panels, menus and cards separate from the canvas.",
    options: [
      { id: "hairline", label: "Hairlines", note: "1px borders, no shadows except menus. Linear." },
      { id: "soft", label: "Hairlines + soft shadow", note: "Borders plus a 1–2px shadow on cards. Vercel." },
      { id: "shadow", label: "Shadows", note: "Layered shadows, faint borders. Stripe." },
    ],
  },
  {
    id: "themes",
    branch: "base",
    gallery: "app",
    question: "Which themes ship?",
    why: "Dark mode is a full second palette and doubles the review surface.",
    options: [
      { id: "both", label: "Light and dark", note: "Both first-class; system default." },
      { id: "light", label: "Light only", note: "" },
      { id: "dark", label: "Dark only", note: "Raycast." },
    ],
  },
  {
    id: "density",
    branch: "app",
    gallery: "app",
    question: "App density?",
    why: "Chrome size, control height and row height move together.",
    options: [
      { id: "compact", label: "Compact", note: "13px chrome, 14px body, 28px controls. Linear." },
      { id: "standard", label: "Standard", note: "14px chrome, 15px body, 32px controls. Vercel, Stripe." },
      { id: "comfortable", label: "Comfortable", note: "15px chrome, 16px body, 36px controls. Notion." },
    ],
  },
  {
    id: "spacing",
    branch: "app",
    gallery: "app",
    question: "Spacing unit?",
    why: "Padding and gaps everywhere scale from one unit. Notion is airy; Linear is tight.",
    options: [
      { id: "tight", label: "Tight", note: "3.5px unit. Dense operator tools. Linear." },
      { id: "regular", label: "Regular", note: "4px unit. The field default." },
      { id: "airy", label: "Airy", note: "5px unit. Generous, document-like. Notion." },
    ],
  },
  {
    id: "shell",
    branch: "app",
    gallery: "app",
    question: "App shell?",
    why: "The one layout decision every screen inherits.",
    options: [
      { id: "sidebar", label: "Sidebar", note: "Grouped left nav, content fills. Linear, Stripe." },
      { id: "topnav", label: "Top nav", note: "Horizontal tabs, centered content. Vercel." },
      { id: "both", label: "Sidebar + top bar", note: "Nav left, context and search on top." },
    ],
  },
  {
    id: "sidebarTone",
    branch: "app",
    gallery: "app",
    question: "Sidebar tone?",
    why: "Linear made theirs a few notches dimmer so content wins.",
    options: [
      { id: "same", label: "Same as canvas", note: "Separated by a hairline only." },
      { id: "tinted", label: "Subtle step", note: "The scale's step 2 in both themes: darker in light, lighter in dark. Notion." },
      { id: "dimmer", label: "Dimmer", note: "Darker in both themes; dark-mode content reads as a raised panel. Linear." },
      { id: "dark", label: "Dark", note: "Dark rail in light mode. Slack-like." },
    ],
  },
  {
    id: "sidebarCollapse",
    branch: "app",
    gallery: "app",
    question: "Does the sidebar collapse?",
    why: "Decides how much screen the content can take and whether nav needs icons.",
    options: [
      { id: "fixed", label: "Fixed", note: "Always expanded. Stripe." },
      { id: "hide", label: "Hide", note: "A toggle hides it fully; nothing on hover. Linear." },
      { id: "peek", label: "Hide, peek on hover", note: "Hidden; hovering the left edge slides it over the content. Notion." },
      { id: "rail", label: "Icon rail", note: "Collapses to a 48px rail; icons are the nav, labels as tooltips. VS Code, Slack." },
      { id: "railExpand", label: "Icon rail, expands on hover", note: "The rail widens over the content when hovered. Supabase." },
    ],
  },
  {
    id: "navIcons",
    branch: "app",
    gallery: "app",
    question: "Icons in the nav?",
    why: "Icons speed scanning and add visual weight; text-only reads calmer.",
    options: [
      { id: "icons", label: "Icons", note: "Icon before every item. Linear, Stripe, Notion." },
      { id: "text", label: "Text only", note: "Labels only. Vercel." },
    ],
  },
  {
    id: "pageTitle",
    branch: "app",
    gallery: "app",
    question: "Page title scale?",
    why: "Decides whether a page reads as a tool view or a document.",
    options: [
      { id: "toolbar", label: "Toolbar", note: "Title in a 40px bar, 14px medium, actions inline. Linear." },
      { id: "standard", label: "Standard", note: "22px title over the content, actions right. Vercel, Stripe." },
      { id: "display", label: "Display", note: "36px title, document-like, generous. Notion." },
    ],
  },
  {
    id: "stats",
    branch: "app",
    gallery: "app",
    question: "Key figures?",
    why: "The most-read numbers on the home screen.",
    options: [
      { id: "strip", label: "Strip", note: "Hairline-separated columns, no containers. Linear." },
      { id: "cards", label: "Cards", note: "Each figure in its own card. Stripe, Vercel." },
      { id: "inline", label: "Inline", note: "One line of label–value pairs under the title. Notion." },
    ],
  },
  {
    id: "trend",
    branch: "app",
    gallery: "app",
    question: "Figures over time?",
    why: "Whether Home shows where a number is going, not just where it is.",
    options: [
      { id: "none", label: "None", note: "The figure only. Linear, Notion." },
      { id: "sparkline", label: "Sparkline", note: "A small line beside each value." },
      { id: "area", label: "Area", note: "A filled area under each figure. Vercel." },
      { id: "chart", label: "One chart", note: "The first figure as a 180px chart, the rest in a row beside it. Stripe." },
      { id: "panel", label: "Chart panel", note: "Figures on top, then a 220px chart with period tabs, axis and a crosshair callout. Analytics-style." },
      { id: "stacked", label: "Stacked by entity", note: "The chart panel, with the first figure split into its entities as a stacked area and a legend; the top edge is the total." },
    ],
  },
  {
    id: "tables",
    branch: "app",
    gallery: "app",
    question: "Table style?",
    why: "Most operator screens are tables.",
    options: [
      { id: "hairline", label: "Hairline rows", note: "1px rules, no fills. Linear, GitHub." },
      { id: "zebra", label: "Zebra", note: "Alternating tint, no rules." },
      { id: "borderless", label: "Borderless", note: "Space only, hover fill. Notion." },
    ],
  },
  {
    id: "rowHover",
    branch: "app",
    gallery: "app",
    question: "Row hover?",
    why: "Fill says rows are targets; none says the table is for reading.",
    options: [
      { id: "fill", label: "Fill", note: "Rows tint on hover and the cursor is a pointer. Linear, Notion." },
      { id: "none", label: "None", note: "No hover state on rows. Vercel." },
    ],
  },
  {
    id: "cards",
    branch: "app",
    gallery: "app",
    question: "Card style?",
    why: "Panels, forms and cards share one treatment.",
    options: [
      { id: "hairline", label: "Bordered", note: "1px border; carries whatever shadow the depth step chose. Linear, Vercel, Stripe." },
      { id: "fill", label: "Filled", note: "Translucent fill, no border. Notion, Raycast." },
    ],
  },
  {
    id: "inputs",
    branch: "app",
    gallery: "app",
    question: "Input style?",
    why: "Every form and the composer.",
    options: [
      { id: "outlined", label: "Outlined", note: "1px border, canvas background. Linear, Vercel." },
      { id: "filled", label: "Filled", note: "Muted background, no border. Notion, Raycast." },
      { id: "underline", label: "Underline", note: "Bottom rule only. Editorial." },
    ],
  },
  {
    id: "buttons",
    branch: "app",
    gallery: "app",
    question: "Button style?",
    why: "Primary is the most-clicked pixel in the product.",
    options: [
      { id: "filled", label: "Filled + ghost", note: "Solid accent primary, ghost secondary. Linear." },
      { id: "outline", label: "Outline-first", note: "Hairline buttons, filled only for the one CTA. Vercel." },
      { id: "soft", label: "Soft", note: "Tinted accent background, accent text. Notion, Raycast." },
    ],
  },
  {
    id: "iconWeight",
    branch: "app",
    gallery: "app",
    question: "Icon weight?",
    why: "Stroke width sets how loud icons are next to 13–15px text.",
    options: [
      { id: "light", label: "Light", note: "1.5px stroke. Linear, Notion." },
      { id: "regular", label: "Regular", note: "2px stroke. Vercel, Stripe." },
      { id: "tiles", label: "Tiles", note: "Icons in small filled rounded tiles. Raycast." },
    ],
  },
  {
    id: "menus",
    branch: "app",
    gallery: "app",
    question: "Menu items?",
    why: "Menus and command lists are where keyboard users live.",
    options: [
      { id: "hints", label: "Icons + shortcuts", note: "Icon left, shortcut right. Linear, Raycast." },
      { id: "plain", label: "Plain", note: "Text only. Vercel, Stripe." },
    ],
  },
  {
    id: "motion",
    branch: "app",
    gallery: "app",
    question: "App motion?",
    why: "None on keyboard and many-times-a-day paths; the question is everything else.",
    options: [
      { id: "none", label: "None", note: "Instant. Raycast." },
      { id: "minimal", label: "Minimal", note: "≤150ms fades on menus and dialogs. Linear." },
      { id: "expressive", label: "Expressive", note: "Springs on overlays and layout. Consumer." },
    ],
  },
  {
    id: "register",
    branch: "landing",
    gallery: "landing",
    question: "Landing register?",
    why: "The landing may carry a different visual language from the app.",
    options: [
      { id: "same", label: "Same as app", note: "The app is the brand. Linear." },
      { id: "dark", label: "Dark showcase", note: "Dark landing, light app. Vercel, Raycast, raindrop." },
      { id: "editorial", label: "Editorial", note: "White, type-led, generous. Stripe." },
      { id: "playful", label: "Playful", note: "Art-led, characters, color. Consumer." },
    ],
  },
  {
    id: "display",
    branch: "landing",
    gallery: "landing",
    question: "Display type?",
    why: "Headlines at 48–72px need their own tracking and weight.",
    options: [
      { id: "same", label: "Same face, tight", note: "UI sans at 500, −2% tracking. Linear." },
      { id: "heavy", label: "Same face, heavy", note: "600–700, −3% tracking. Punchier." },
      { id: "mono", label: "Mono headlines", note: "The mono as display. Reads technical." },
      { id: "giant", label: "Giant display", note: "96–128px centered product statements. Apple, Cash App." },
    ],
  },
  {
    id: "displayCase",
    branch: "landing",
    gallery: "landing",
    question: "Headline case?",
    why: "Independent of weight; lowercase reads indie and craft-led.",
    options: [
      { id: "written", label: "As written", note: "Sentence case as in the copy deck." },
      { id: "lowercase", label: "Lowercase", note: "The whole headline set lowercase. raindrop." },
    ],
  },
  {
    id: "hero",
    branch: "landing",
    gallery: "landing",
    question: "Hero composition?",
    why: "The one screen most visitors see.",
    options: [
      { id: "shot", label: "Headline + product shot", note: "Copy above, the app below. Linear." },
      { id: "split", label: "Split", note: "Copy left, visual right." },
      { id: "device", label: "Device frame", note: "The app inside a laptop or phone." },
      { id: "scene", label: "Animated scene", note: "A bespoke animated piece is the visual." },
      { id: "type", label: "Typographic", note: "Headline only, oversized. No visual." },
      { id: "media", label: "Full-bleed media", note: "Giant copy followed by an edge-to-edge product or photographic stage. Apple, Airbnb." },
    ],
  },
  {
    id: "heroMotion",
    branch: "landing",
    gallery: "landing",
    question: "Hero motion?",
    why: "Motion is the difference between a screenshot and a product that feels alive.",
    options: [
      { id: "static", label: "Static", note: "No motion." },
      { id: "entrance", label: "Entrance", note: "Staggered fade-up once on load." },
      { id: "ambient", label: "Ambient", note: "Slow continuous drift: gradients, floating pieces." },
      { id: "scroll", label: "Scroll-driven", note: "The visual transforms as you scroll." },
      { id: "interactive", label: "Interactive", note: "Responds to the cursor; things walk around." },
      { id: "interactiveScroll", label: "Interactive + scroll", note: "Responds to the cursor, and collapses into the product as you scroll. raindrop." },
    ],
  },
  {
    id: "background",
    branch: "landing",
    gallery: "landing",
    question: "Background treatment?",
    why: "Sets depth behind the hero without competing with it.",
    options: [
      { id: "flat", label: "Flat", note: "Canvas only." },
      { id: "glow", label: "Glow", note: "Accent-tinted radial gradient." },
      { id: "grid", label: "Grid", note: "Faint line grid or dot matrix." },
      { id: "grain", label: "Grain", note: "Noise texture over a gradient." },
      { id: "scene", label: "Scene", note: "Illustrated or 3D backdrop." },
    ],
  },
  {
    id: "rhythm",
    branch: "landing",
    gallery: "landing",
    question: "Section rhythm?",
    why: "How the page reads below the fold.",
    options: [
      { id: "alternating", label: "Alternating", note: "Claim + visual, sides swap each section. Linear." },
      { id: "bento", label: "Bento", note: "Grid of cards, each a feature. Apple, Vercel." },
      { id: "fullbleed", label: "Full-bleed", note: "Each section a full-width showcase." },
      { id: "sticky", label: "Sticky scroll", note: "Visual pinned while claims scroll past." },
      { id: "chapters", label: "Scene chapters", note: "A sticky product stage changes as card-like claims advance. Raindrop, Apple." },
    ],
  },
  {
    id: "frames",
    branch: "landing",
    gallery: "landing",
    question: "Product shots in frames?",
    why: "A frame says 'this is software'; no frame says 'this is the thing itself'.",
    options: [
      { id: "none", label: "Bare", note: "Hairline and radius only. Linear." },
      { id: "browser", label: "Browser chrome", note: "Three dots and a URL bar." },
      { id: "laptop", label: "Laptop", note: "A MacBook outline." },
      { id: "phone", label: "Phone", note: "A phone outline; implies mobile." },
    ],
  },
  {
    id: "characters",
    branch: "landing",
    gallery: "landing",
    question: "Floating pieces or characters?",
    why: "Personality. The pieces must come from the product, never from a stock set.",
    options: [
      { id: "none", label: "None", note: "The product is the only visual." },
      { id: "icons", label: "Floating icons", note: "Product objects drift around the hero." },
      { id: "characters", label: "Characters", note: "Animated figures doing tasks. raindrop." },
      { id: "shapes", label: "Abstract", note: "Geometric shapes and lines." },
    ],
  },
  {
    id: "proof",
    branch: "landing",
    gallery: "landing",
    question: "Proof section?",
    why: "What convinces after the hero.",
    options: [
      { id: "logos", label: "Logos", note: "'Trusted by' row. Linear." },
      { id: "numbers", label: "Numbers", note: "Three big figures." },
      { id: "quotes", label: "Quotes", note: "One or three testimonials." },
      { id: "none", label: "None", note: "" },
    ],
  },
  {
    id: "cta",
    branch: "landing",
    gallery: "landing",
    question: "Call to action?",
    why: "One decision the visitor makes.",
    options: [
      { id: "single", label: "Single", note: "One primary button." },
      { id: "pair", label: "Primary + secondary", note: "Get started, plus a look-first option." },
      { id: "email", label: "Email capture", note: "Waitlist or sign-up field." },
    ],
  },
];

export const STEP_BY_ID: Record<StepId, Step> = Object.fromEntries(STEPS.map((s) => [s.id, s])) as Record<StepId, Step>;

/** What each reference product does at every step. */
export const PRESETS: Record<string, ResolvedChoices> = {
  linear: {
    reference: "linear", typeface: "inter", mono: "geist-mono", neutral: "cool", contrast: "standard", accent: "indigo",
    radius: "medium", depth: "hairline", themes: "both",
    density: "compact", spacing: "tight", shell: "sidebar", sidebarTone: "dimmer", sidebarCollapse: "hide", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "none", tables: "hairline", rowHover: "fill", cards: "hairline", inputs: "outlined", buttons: "filled",
    iconWeight: "light", menus: "hints", motion: "minimal",
    register: "same", display: "same", displayCase: "written", hero: "shot", heroMotion: "entrance", background: "flat", rhythm: "alternating",
    frames: "none", characters: "none", proof: "logos", cta: "pair",
  },
  vercel: {
    reference: "vercel", typeface: "geist", mono: "geist-mono", neutral: "neutral", contrast: "standard", accent: "neutral",
    radius: "medium", depth: "soft", themes: "both",
    density: "standard", spacing: "regular", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "text", pageTitle: "standard",
    stats: "cards", trend: "area", tables: "hairline", rowHover: "none", cards: "hairline", inputs: "outlined", buttons: "outline",
    iconWeight: "regular", menus: "plain", motion: "minimal",
    register: "dark", display: "heavy", displayCase: "written", hero: "shot", heroMotion: "entrance", background: "grid", rhythm: "bento",
    frames: "none", characters: "none", proof: "logos", cta: "pair",
  },
  stripe: {
    reference: "stripe", typeface: "inter", mono: "jetbrains", neutral: "cool", contrast: "standard", accent: "violet",
    radius: "round", depth: "shadow", themes: "light",
    density: "standard", spacing: "regular", shell: "sidebar", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "icons", pageTitle: "standard",
    stats: "cards", trend: "chart", tables: "hairline", rowHover: "fill", cards: "hairline", inputs: "outlined", buttons: "filled",
    iconWeight: "regular", menus: "plain", motion: "minimal",
    register: "editorial", display: "heavy", displayCase: "written", hero: "split", heroMotion: "ambient", background: "glow", rhythm: "alternating",
    frames: "browser", characters: "icons", proof: "logos", cta: "pair",
  },
  notion: {
    reference: "notion", typeface: "inter", mono: "system-mono", neutral: "warm", contrast: "soft", accent: "blue",
    radius: "sharp", depth: "hairline", themes: "both",
    density: "comfortable", spacing: "airy", shell: "sidebar", sidebarTone: "tinted", sidebarCollapse: "peek", navIcons: "icons", pageTitle: "display",
    stats: "inline", trend: "none", tables: "borderless", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "light", menus: "plain", motion: "minimal",
    register: "editorial", display: "heavy", displayCase: "written", hero: "split", heroMotion: "static", background: "flat", rhythm: "alternating",
    frames: "none", characters: "characters", proof: "logos", cta: "single",
  },
  raycast: {
    reference: "raycast", typeface: "inter", mono: "jetbrains", neutral: "neutral", contrast: "standard", accent: "crimson",
    radius: "round", depth: "soft", themes: "dark",
    density: "compact", spacing: "regular", shell: "sidebar", sidebarTone: "tinted", sidebarCollapse: "rail", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "none", tables: "hairline", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "soft",
    iconWeight: "tiles", menus: "hints", motion: "none",
    register: "dark", display: "heavy", displayCase: "written", hero: "device", heroMotion: "scroll", background: "glow", rhythm: "fullbleed",
    frames: "laptop", characters: "none", proof: "numbers", cta: "single",
  },
  ramp: {
    reference: "ramp", typeface: "inter", mono: "geist-mono", neutral: "neutral", contrast: "high", accent: "green",
    radius: "sharp", depth: "hairline", themes: "light",
    density: "compact", spacing: "regular", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "text", pageTitle: "toolbar",
    stats: "strip", trend: "area", tables: "borderless", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "regular", menus: "plain", motion: "minimal",
    register: "editorial", display: "heavy", displayCase: "written", hero: "media", heroMotion: "entrance", background: "grid", rhythm: "bento",
    frames: "none", characters: "none", proof: "numbers", cta: "email",
  },
  apple: {
    reference: "apple", typeface: "system", mono: "system-mono", neutral: "neutral", contrast: "high", accent: "blue",
    radius: "pill", depth: "soft", themes: "light",
    density: "comfortable", spacing: "airy", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "text", pageTitle: "display",
    stats: "cards", trend: "none", tables: "borderless", rowHover: "none", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "regular", menus: "plain", motion: "expressive",
    register: "editorial", display: "giant", displayCase: "written", hero: "media", heroMotion: "ambient", background: "flat", rhythm: "chapters",
    frames: "none", characters: "none", proof: "none", cta: "pair",
  },
  raindrop: {
    reference: "raindrop", typeface: "inter", mono: "geist-mono", neutral: "neutral", contrast: "standard", accent: "green",
    radius: "medium", depth: "hairline", themes: "dark",
    density: "compact", spacing: "tight", shell: "sidebar", sidebarTone: "dimmer", sidebarCollapse: "rail", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "chart", tables: "hairline", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "soft",
    iconWeight: "light", menus: "hints", motion: "minimal",
    register: "dark", display: "heavy", displayCase: "lowercase", hero: "shot", heroMotion: "interactiveScroll", background: "flat", rhythm: "chapters",
    frames: "none", characters: "characters", proof: "numbers", cta: "pair",
  },
  mercury: {
    reference: "mercury", typeface: "instrument", mono: "system-mono", neutral: "warm", contrast: "soft", accent: "orange",
    radius: "round", depth: "shadow", themes: "light",
    density: "comfortable", spacing: "airy", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "text", pageTitle: "display",
    stats: "inline", trend: "area", tables: "borderless", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "light", menus: "plain", motion: "minimal",
    register: "editorial", display: "giant", displayCase: "written", hero: "media", heroMotion: "ambient", background: "grain", rhythm: "alternating",
    frames: "none", characters: "shapes", proof: "quotes", cta: "pair",
  },
  cashapp: {
    reference: "cashapp", typeface: "system", mono: "system-mono", neutral: "neutral", contrast: "high", accent: "green",
    radius: "pill", depth: "soft", themes: "both",
    density: "comfortable", spacing: "airy", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "icons", pageTitle: "display",
    stats: "cards", trend: "none", tables: "borderless", rowHover: "none", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "regular", menus: "plain", motion: "expressive",
    register: "playful", display: "giant", displayCase: "written", hero: "device", heroMotion: "ambient", background: "flat", rhythm: "fullbleed",
    frames: "phone", characters: "shapes", proof: "numbers", cta: "single",
  },
  airbnb: {
    reference: "airbnb", typeface: "system", mono: "system-mono", neutral: "warm", contrast: "soft", accent: "crimson",
    radius: "pill", depth: "soft", themes: "light",
    density: "comfortable", spacing: "airy", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "icons", pageTitle: "standard",
    stats: "cards", trend: "none", tables: "borderless", rowHover: "none", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "regular", menus: "plain", motion: "minimal",
    register: "playful", display: "heavy", displayCase: "written", hero: "media", heroMotion: "entrance", background: "flat", rhythm: "bento",
    frames: "none", characters: "icons", proof: "quotes", cta: "pair",
  },
  figma: {
    reference: "figma", typeface: "inter", mono: "jetbrains", neutral: "neutral", contrast: "high", accent: "orange",
    radius: "round", depth: "hairline", themes: "both",
    density: "standard", spacing: "regular", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "icons", pageTitle: "display",
    stats: "inline", trend: "none", tables: "borderless", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "filled",
    iconWeight: "regular", menus: "hints", motion: "expressive",
    register: "playful", display: "giant", displayCase: "written", hero: "media", heroMotion: "interactive", background: "scene", rhythm: "bento",
    frames: "browser", characters: "shapes", proof: "logos", cta: "pair",
  },
  cursor: {
    reference: "cursor", typeface: "geist", mono: "geist-mono", neutral: "warm", contrast: "standard", accent: "neutral",
    radius: "medium", depth: "hairline", themes: "dark",
    density: "compact", spacing: "tight", shell: "sidebar", sidebarTone: "dimmer", sidebarCollapse: "rail", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "none", tables: "hairline", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "soft",
    iconWeight: "light", menus: "hints", motion: "minimal",
    register: "dark", display: "heavy", displayCase: "written", hero: "shot", heroMotion: "ambient", background: "grid", rhythm: "alternating",
    frames: "none", characters: "none", proof: "logos", cta: "pair",
  },
  supabase: {
    reference: "supabase", typeface: "inter", mono: "jetbrains", neutral: "cool", contrast: "standard", accent: "green",
    radius: "medium", depth: "hairline", themes: "both",
    density: "compact", spacing: "tight", shell: "sidebar", sidebarTone: "dimmer", sidebarCollapse: "rail", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "chart", tables: "hairline", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "soft",
    iconWeight: "light", menus: "hints", motion: "minimal",
    register: "dark", display: "heavy", displayCase: "written", hero: "shot", heroMotion: "entrance", background: "grid", rhythm: "bento",
    frames: "browser", characters: "none", proof: "logos", cta: "pair",
  },
  posthog: {
    reference: "posthog", typeface: "inter", mono: "jetbrains", neutral: "warm", contrast: "standard", accent: "orange",
    radius: "round", depth: "hairline", themes: "both",
    density: "compact", spacing: "regular", shell: "sidebar", sidebarTone: "tinted", sidebarCollapse: "rail", navIcons: "icons", pageTitle: "toolbar",
    stats: "strip", trend: "chart", tables: "hairline", rowHover: "fill", cards: "fill", inputs: "filled", buttons: "soft",
    iconWeight: "regular", menus: "hints", motion: "expressive",
    register: "playful", display: "heavy", displayCase: "written", hero: "shot", heroMotion: "ambient", background: "grain", rhythm: "bento",
    frames: "browser", characters: "characters", proof: "numbers", cta: "pair",
  },
  attio: {
    reference: "attio", typeface: "inter", mono: "geist-mono", neutral: "neutral", contrast: "high", accent: "neutral",
    radius: "sharp", depth: "hairline", themes: "both",
    density: "standard", spacing: "regular", shell: "sidebar", sidebarTone: "same", sidebarCollapse: "hide", navIcons: "icons", pageTitle: "toolbar",
    stats: "inline", trend: "none", tables: "borderless", rowHover: "fill", cards: "hairline", inputs: "outlined", buttons: "filled",
    iconWeight: "light", menus: "hints", motion: "minimal",
    register: "editorial", display: "heavy", displayCase: "written", hero: "shot", heroMotion: "entrance", background: "flat", rhythm: "alternating",
    frames: "none", characters: "none", proof: "logos", cta: "pair",
  },
  resend: {
    reference: "resend", typeface: "geist", mono: "geist-mono", neutral: "neutral", contrast: "high", accent: "neutral",
    radius: "medium", depth: "hairline", themes: "dark",
    density: "compact", spacing: "tight", shell: "topnav", sidebarTone: "same", sidebarCollapse: "fixed", navIcons: "text", pageTitle: "toolbar",
    stats: "strip", trend: "none", tables: "hairline", rowHover: "fill", cards: "hairline", inputs: "outlined", buttons: "outline",
    iconWeight: "light", menus: "plain", motion: "minimal",
    register: "dark", display: "heavy", displayCase: "written", hero: "split", heroMotion: "entrance", background: "grid", rhythm: "bento",
    frames: "browser", characters: "none", proof: "logos", cta: "pair",
  },
};

export function resolveChoices(choices: Choices): ResolvedChoices {
  const preset = PRESETS[choices.reference ?? "linear"] ?? PRESETS.linear!;
  return { ...preset, ...(choices as Record<StepId, string>) };
}

/** Steps whose user choice differs from the reference default. */
export function deviations(choices: Choices): StepId[] {
  const preset = PRESETS[choices.reference ?? "linear"] ?? PRESETS.linear!;
  return STEPS.filter((s) => s.id !== "reference" && choices[s.id] !== undefined && choices[s.id] !== preset[s.id]).map((s) => s.id);
}
