import type { Archetype } from "@/tree/types";
import type { Surfaces } from "../schema";

/** Context matches each existing archetype thread rather than inventing another conversation. */
export const CONVERSATION_SURFACE: Record<Archetype, Surfaces["conversation"]> = {
  workspace: { title: "billing incident", action: "Add teammate", empty: "No incident messages yet. Share what you are seeing.", context: { title: "billing · elevated latency", body: "Investigating the deploy that changed the connection pool.", facts: [{ label: "Service", value: "billing" }, { label: "State", value: "Investigating" }, { label: "Started", value: "14:09" }] } },
  feed: { title: "Sourdough replies", action: "Share post", empty: "No replies yet. Ask a question about the loaf.", context: { title: "Sourdough crumb at 78% hydration", body: "Priya's third loaf this month; proof timings are being discussed in the replies.", facts: [{ label: "Author", value: "Priya Nair" }, { label: "Topic", value: "Baking" }, { label: "Media", value: "Photo" }] } },
  commerce: { title: "Message Tern & Clay", action: "View order", empty: "No messages yet. Ask the maker about your order.", context: { title: "Speckled stoneware mug", body: "Confirming the oat glaze and care instructions before the maker ships.", facts: [{ label: "Maker", value: "Tern & Clay" }, { label: "Price", value: "$34" }, { label: "Ships", value: "Thursday" }] } },
  reader: { title: "Practice at the market", action: "Review words", empty: "No practice answers yet. Begin with a greeting.", context: { title: "Unit 3 · At the market", body: "Practice asking for quantities and prices in Portuguese.", facts: [{ label: "Language", value: "Portuguese" }, { label: "Topic", value: "Quantities" }, { label: "Mode", value: "Dialogue" }] } },
  media: { title: "Field Notes discussion", action: "Play episode", empty: "No episode notes yet. Leave a question for the host.", context: { title: "Field Notes, Ep. 31", body: "A tide pool recording with a species list linked in the episode notes.", facts: [{ label: "Host", value: "Dr. Imani Cole" }, { label: "Duration", value: "38:20" }, { label: "Format", value: "Podcast" }] } },
  companion: { title: "Ashen Wardens clan", action: "View raid", empty: "No clan messages yet. Say when you can join the raid.", context: { title: "Sunken Crypt raid", body: "The clan is assembling a party and checking power and supplies.", facts: [{ label: "Starts", value: "20:00" }, { label: "Power needed", value: "9,000" }, { label: "Bring", value: "Ember charms" }] } },
  canvas: { title: "Welcome frame comments", action: "Open frame", empty: "No frame comments yet. Select a layer and leave a note.", context: { title: "Welcome / Sign in flow", body: "Reviewing small-screen hero cropping and the continue button above the keyboard.", facts: [{ label: "Board", value: "Welcome" }, { label: "Frame width", value: "320 px" }, { label: "Review", value: "Open" }] } },
  conversation: { title: "Signups by week", action: "Share thread", empty: "No messages yet. Ask for an analysis or invite a teammate.", context: { title: "Monday update", body: "Weekly signups and cancellations, with a requested split by plan.", facts: [{ label: "Range", value: "8 weeks" }, { label: "Week starts", value: "Monday" }, { label: "Next", value: "Split by plan" }] } },
  utility: { title: "Conversion help", action: "Save result", empty: "No questions yet. Enter an amount and the units you need.", context: { title: "500 ml in kitchen units", body: "Converting a metric volume to cups and fluid ounces using exact factors.", facts: [{ label: "Input", value: "500 ml" }, { label: "Cups", value: "2.11" }, { label: "Fluid ounces", value: "16.91" }] } },
};
